### ISSUE TITLE
Is the "tuple and shape" example out of date?

### ISSUE THREAD

**Issue by ghiculescu** [sorbet/sorbet.run#21]
[Here's the current example](https://sorbet.run/#%23%20typed%3A%20true%0A%23%20This%20example%20shows%20some%20of%20our%20incomplete%20additions%20to%20the%20type%20system%0A%23%20but%20hopefully%20gives%20you%20an%20idea%20of%20the%20posibilities.%0Aextend%20T%3A%3ASig%0Asig%20do%0A%20%20params(arg%3A%20%5BInteger%2C%20String%2C%20Array%5D)%0A%20%20.returns(Integer)%0Aend%0Adef%20tuple_method(arg)%0A%20%20arg%5B0%5D%20%23%20This%20currently%20returns%20T.unsafe%20so%20isn't%20checked.%0Aend%0A%0Asig%20do%0A%20%20params(arg%3A%20%7B%0A%20%20%20%20my_string%3A%20String%2C%0A%20%20%20%20my_int%3A%20Integer%2C%0A%20%20%7D)%0A%20%20.returns(Integer)%0Aend%0Adef%20shape_method(arg)%0A%20%20arg%5B%3Amy_int%5D%20%23%20This%20currently%20returns%20T.unsafe%20so%20isn't%20checked.%0Aend%0A%0Atuple%20%3D%20%5B1%2C%20'2'%2C%20%5B3%5D%5D%0A%23%20This%20is%20not%20yet%20working%20in%20this%20version.%0A%23%20We%20have%20a%20prototype%20that%20would%20make%20it%20work%2C%20but%20it%20is%20too%20strict.%0A%23%20We%20are%20still%20working%20out%20details%20of%20how%20permissive%20or%20strict%20we%20should%20be.%0A%23%20T.assert_type!(tuple%5B0%5D%2C%20Integer)%0Atuple_method(tuple)%0A%23%20If%20the%20tuples%20don't%20match%2C%20we%20error%3A%0Atuple_method(%5B1%2C%202%2C%203%5D)%0A%0Ashape%20%3D%20%7Bmy_string%3A%20'value'%2C%20my_int%3A%200%7D%0A%23%20Same%20with%20shapes.%0A%23%20T.assert_type!(shape%5B%3Amy_string%5D%2C%20String)%0Ashape_method(shape)%0A%23%20We%20do%20check%20shapes%20have%20all%20the%20keys%20you%20required.%0Ashape_method(%7Bmy_string%3A%20'value'%7D)) that's live on sorbet.run and accessible from the Examples dropdown.

Note that there's two errors, as well as a bunch of comments explaining code that currently doesn't work.

I removed some of these comments, and uncommented some of the "not working" code and it seemed to work fine. See [this version](https://sorbet.run/#%23%20typed%3A%20true%0A%23%20This%20example%20shows%20some%20of%20our%20incomplete%20additions%20to%20the%20type%20system%0A%23%20but%20hopefully%20gives%20you%20an%20idea%20of%20the%20posibilities.%0Aextend%20T%3A%3ASig%0Asig%20do%0A%20%20params(arg%3A%20%5BInteger%2C%20String%2C%20Array%5D)%0A%20%20.returns(Integer)%0Aend%0Adef%20tuple_method(arg)%0A%20%20arg%5B0%5D%0Aend%0A%0Asig%20do%0A%20%20params(arg%3A%20%7B%0A%20%20%20%20my_string%3A%20String%2C%0A%20%20%20%20my_int%3A%20Integer%2C%0A%20%20%7D)%0A%20%20.returns(Integer)%0Aend%0Adef%20shape_method(arg)%0A%20%20arg%5B%3Amy_int%5D%0Aend%0A%0Atuple%20%3D%20%5B1%2C%20'2'%2C%20%5B3%5D%5D%0AT.assert_type!(tuple%5B0%5D%2C%20Integer)%0Atuple_method(tuple)%0AT.assert_type!(tuple_method(tuple)%2C%20Integer)%0A%23%20If%20the%20tuples%20don't%20match%2C%20we%20error%3A%0Atuple_method(%5B1%2C%202%2C%203%5D)%0A%0Ashape%20%3D%20%7Bmy_string%3A%20'value'%2C%20my_int%3A%200%7D%0A%23%20This%20is%20not%20yet%20working%20in%20this%20version.%0A%23%20We%20have%20a%20prototype%20that%20would%20make%20it%20work%2C%20but%20it%20is%20too%20strict.%0A%23%20We%20are%20still%20working%20out%20details%20of%20how%20permissive%20or%20strict%20we%20should%20be.%0A%23%20If%20you%20uncomment%20the%20next%20line%2C%20it%20will%20error%20even%20though%20the%20assertion%20seems%20correct.%0A%23%20T.assert_type!(shape%5B%3Amy_string%5D%2C%20String)%0A%0A%23%20This%20checks%20works%20fine%2C%20though%3A%0Ashape_method(shape)%0A%23%20We%20do%20check%20shapes%20have%20all%20the%20keys%20you%20required.%0Ashape_method(%7Bmy_string%3A%20'value'%7D)%0A%23%20And%20that%20they%20have%20the%20right%20types.%0Ashape_method(%7Bmy_string%3A%20'value'%2C%20my_int%3A%20'1'%7D)), which does more but has exactly the same errors.

Does this mean the example is out of date, and should be updated, potentially to match my new one?

There is still one definite issue there, which is that if you define a hash and then try to access a key, the key is untyped ([simpler replication here](https://sorbet.run/#shape%20%3D%20%7Bmy_string%3A%20'value'%2C%20my_int%3A%200%7D%0AT.assert_type!(shape%5B%3Amy_string%5D%2C%20String))) - I'm sure this issue isn't news to the Sorbet team though since it was in the original example too.

**Comment by aisamanra** [comment]
The errors in this example are on purpose, but the example was out-of-date in other ways: I went ahead and fixed it in #34.
